
import BodyWrapper from '../components/bodyWrapper'; 
import Header from "../components/header";
import PageTransitionWrapper from '../components/PageTransitionWrapper'; 
import './globals.css';


export const metadata = {
  title: 'Manhattan Muse',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/favicon.ico',
        sizes: 'any',
      }
    ],
    shortcut: '/favicon.ico',
  },
};
export default function RootLayout({ children }) {

 
  return (
   <html lang="en">
      
      <body>
        <div className="layout">
          <Header />
          <PageTransitionWrapper>
            {children}
          </PageTransitionWrapper>
        </div>
      </body>
    </html>
  );
}