spring:
  application:
    name: creative-space-finder
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      # 1 to 8 connections for better concurrent user use (load testing)
      maximum-pool-size: 8           # Max pool size of 8 for medium load
      minimum-idle: 2                # Keep 2 connections ready at once
      connection-timeout: 15000      # 15 seconds
      idle-timeout: 60000            # 1 minute
      max-lifetime: 300000           # 5 minutes
      leak-detection-threshold: 20000 # 20 seconds for detecting leaks
      # Connection validation
      connection-test-query: SELECT 1
      validation-timeout: 3000       # 3 seconds validation
      auto-commit: true             
      pool-name: "ScaledHikariPool"  # Pool name  
      # Connection cleanup properties
      keepalive-time: 30000          # 30 seconds keepalive
      initialization-fail-timeout: 5000 # 5 seconds

  jpa:
    hibernate:
      ddl-auto: validate             # Validate for safety
    show-sql: false                  # Disable SQL logging to reduce noise
    open-in-view: false              # Avoid leaks
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  # Avoids JDBC metadata lookup
        jdbc:
          time_zone: UTC
          batch_size: 25             
        connection:
          provider_disables_autocommit: false  # Ensure autocommit works
        # Minimise connection usage during startup
        temp:
          use_jdbc_metadata_defaults: false
        boot:
          allow_jdbc_metadata_access: false

  # Graceful shutdown handling
  lifecycle:
    timeout-per-shutdown-phase: 45s

  # Session configuration for admin authentication
  session:
    store-type: memory
    timeout: 24h

  # Async task  
  task:
    execution:
      pool:
        core-size: 3                
        max-size: 8                  
        queue-capacity: 15           
        thread-name-prefix: "async-"
        keep-alive: 90s             

# Admin credentials configuration
admin:
  username: ${ADMIN_USERNAME}
  password:
    hash: ${ADMIN_PASSWORD_HASH}

openweather:
  api-key: ${OPENWEATHER_API_KEY}

server:
  port: 8080
  servlet:
    context-path: /
    session:
      tracking-modes: cookie
      cookie:
        secure: false 
        http-only: true
        max-age: 86400  # 24 hours
  # Shutdown handling
  shutdown: graceful
  tomcat:
    # Handles 50-60 concurrent users
    connection-timeout: 30000  
    max-connections: 150            
    threads:
      max: 250                       
      min-spare: 15                 
    processor-cache: 300            
    accept-count: 150               

# Logging for debugging and performance
logging:
  level:
    com.creativespacefinder.manhattan: INFO
    org.springframework.web: INFO           
    org.hibernate.SQL: WARN                 
    org.hibernate.orm.deprecation: WARN     
    com.zaxxer.hikari: INFO                 
    com.zaxxer.hikari.pool: WARN            
    # Cache and async debugging
    org.springframework.cache: INFO        
    com.github.benmanes.caffeine: INFO     
    org.springframework.scheduling: INFO    # Show async task execution
    org.springframework.core.task: INFO    

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,shutdown,caches
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
    caches:
      enabled: true  # Enable cache endpoint for debugging

# ML configuration for model
ml:
  predict:
    url: ${ML_PREDICT_URL:http://ml-service.default.svc.cluster.local:8000/predict_batch}
    # Timeout settings
    timeout:
      connect: 35000    # 35 seconds to connect
      read: 150000      # 2.5 minutes to read response

# Cache warming configuration
cache:
  warming:
    async: true
    batch-size: 7
    delay-between-batches: 2500
    max-duration-minutes: 25
