name: Lint Backend

on:
  pull_request:
    branches: [main]
    paths: ['backend/**']

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Checkstyle
        run: mvn checkstyle:check   
        working-directory: backend

