name: Lint Data

on:
  pull_request:
    branches: [main]
    paths: ['data-analytics/**']  

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: data-analytics

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install linters
        run: pip install black flake8

      - name: Run Black (check format)
        run: black --check .

      - name: Run Flake8 (linting)
        run: flake8 .
